### PR TITLE
corrected titles where there was a whitespace missing

### PR DESCRIPTION
**Pull request by sjulez**
Hey, I witnessed malformed markdown down your document and thought "why not give this a quick fix?". So here it is.

Regards

### CODE REVIEW

**Comment by snori74** [comment]
Cool! I haven't ever processed a Pull Request before, so I'll need to do
some reading fist, but I'm very happy to accept these fixes.

 - Steve (snori74)

**Comment by sjulez** [comment]
It's my first contribution to a project like this, too :-P

**Comment by janbue** [comment]
As this is outdated I will close this pull request.

**Comment by snori74** [comment]
Ta

**Pull request closed without merging**
