### PR TITLE
Collate lessons

### PR DESCRIPTION
**Pull request by seasonedfish**
Without leading zeros in their numbers, the lessons show up out of order. This PR collates the lessons by adding leading zeros to their numbers.

Old file names
image

New file names
image

### CODE REVIEW

**Comment by janbue** [comment]
As this has its advantages it might be not as useful as it seems if the posting process should be automated. Might need to think about that @snori74 .

**Comment by snori74** [comment]
> As this has its advantages it might be not as useful as it seems if the posting process should be automated. Might need to think about that @snori74 .

It *is* useful for those looking up this repo for the lessons. For our automation, the main thing is that we don't rename again once we go 'live' with a bot.

**Comment by snori74** [comment]
Have now done this manually myself - thanks "tactlessfish", this makes sense.

**Comment by janbue** [comment]
I will close this pull request, as it's already done without merging

**Pull request closed without merging**
